Suppress Werror=calloc-transposed-args
Suppress the false positive,
    drivers/soc/tegra/fuse/fuse-tegra.c:130:65: error: ‘kmemdup_array’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
      130 |         fuse->lookups = kmemdup_array(fuse->soc->lookups, sizeof(*fuse->lookups),
          |                                                                 ^
    drivers/soc/tegra/fuse/fuse-tegra.c:130:65: note: earlier argument should specify number of elements, later size of each element
    cc1: all warnings being treated as errors

For more details, check commit 0ee14725471c ("mm/util: Swap kmemdup_array() arguments").